### ISSUE TITLE
is there a file missing in git - ontology_table_indices.sql

### ISSUE THREAD

**Issue by mim18** [kvb2univpitt/ontology-store#1]

**Comment by kvb2univpitt** [comment]
It should be there when you check out:
https://github.com/kvb2univpitt/ontology-store/blob/main/ontology-store-ws/src/main/resources/sql/ontology_table_indices.sql

**Comment by kvb2univpitt** [comment]
The new location is here: https://github.com/kvb2univpitt/ontology-store/blob/main/ontology-store-ws/src/main/resources/ont/ontology_table_indices.sql
