### ISSUE TITLE
Make sure to check for admin privileges before allowing ontology install.

### ISSUE THREAD

**Issue by mim18** [kvb2univpitt/ontology-store#2]

**Comment by mim18** [comment]
You do not have to have admin privileges to download files to a local directory. Installation into i2b2 always requires the user to have admin privileges.

**Comment by kvb2univpitt** [comment]
This will require a significant amount of work since I have to create another datasource for the PM cell to look up  the current user and extract the function that validates user from the core-server code over to the ontology web services.  I will do my best to get this done by the 15th of this month.  But, I can't promise.

**Comment by mim18** [comment]
Please check the plugin infrastructure first I believe it has functionality that allows you to prohibit who can see what plugins. I would prefer you use that feature. 

Don't worry about the ability to download w/o installing now. we will allow download only from the website instead of the plugin

**Comment by kvb2univpitt** [comment]
> Don't worry about the ability to download w/o installing now. we will allow download only from the website instead of the plugin

Right now we do have the ability to download without installing.  The download and installation are independent.

OK.  I'll look into the front-end infrastructure first.  It's not an ideal way of doing it since it can be by-pass just by calling the web services directly.  We can always circle back and implement the back-end part later.

**Comment by mim18** [comment]
I think if your code always checks for the auth token it would not work from the backend either

**Comment by kvb2univpitt** [comment]
Isn't that how i2b2 work?  After you login, every subsequent request passes ***domain***, ***username***, and ***session key*** to the PM Cell to verify.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:request xmlns:ns3="http://www.i2b2.org/xsd/hive/msg/1.1/" xmlns:ns4="http://www.i2b2.org/xsd/cell/ont/1.1/" xmlns:ns2="http://www.i2b2.org/xsd/hive/plugin/">
    <message_header>
        <proxy>
            <redirect_url>http://services.i2b2.org/i2b2/services/OntologyService/getSchemes</redirect_url>
        </proxy>
        ...
        <security>
            <domain>i2b2demo</domain>
            <username>demo</username>
            <password is_token="true" token_ms_timeout="1800000">SessionKey:9imxGONQ7ln7MqJw3HRT</password>
        </security>
        ...
    </message_header>
    <request_header>
        <result_waittime_ms>180000</result_waittime_ms>
    </request_header>
    <message_body>
        <ns4:get_schemes type="default"/>
    </message_body>
</ns3:request>
```

Here's a snippet of the code from i2b2 PM Cell that I was going to use for verifying admin user.  Note that I am only going to use part of the code where I can retrieve the ```user``` and verify that the user is admin by calling ```user.isIsAdmin()```.

```java
if (password.startsWith("SessionKey:")) {
        String sessionKey = password.replace("SessionKey:", "");
        log.debug("Encrypted Session key: " + sessionKey + " passed in for validation.");
        if (rmt.getPassword().getTokenMsTimeout() == null) {
            rmt.getPassword().setTokenMsTimeout(1800000);
        }
        if (verifySession(pmDb, rmt.getPassword().getTokenMsTimeout(), sessionKey, rmt.getUsername()) == false) {
            throw new Exception("Session invalid");
        }

        //get the user from the service
        UserType user = null;
        for (it = pmDb.getUser(rmt.getUsername(), null).iterator(); it.hasNext();) {
            user = (UserType) it.next();
        }

        //user = userManagerService.getUserByUserName(k.getUsername());
        if (user == null) {
            log.debug("Did not find user: " + rmt.getUsername());
            throw new Exception("Username does not exist");
        }
        //check the password

        //everything is good so just return the same session key and the other info
        uType.setFullName(user.getFullName());
        uType.setUserName(rmt.getUsername());
        uType.setDomain(rmt.getDomain());
        uType.setIsAdmin(user.isIsAdmin());
        PasswordType passType = new PasswordType();
        passType.setIsToken(true);
        passType.setValue(password);
        passType.setTokenMsTimeout(rmt.getPassword().getTokenMsTimeout());
        uType.setPassword(passType); //"SessionKey:"+sessionKey); //return the key instead of password
        //uType.setKey(rmt.getPassword()); //return password so client can reaunthenticate later
}
```

Or, did I misunderstood and this is not what you're asking for?

**Comment by mim18** [comment]
correct. I was responding to your comment
"It's not an ideal way of doing it since it can be by-pass just by calling the web services directly. We can always circle back and implement the back-end part later."
It won't be by pass-able by calling a webservice if you use that code.

**Comment by kvb2univpitt** [comment]
For the web client (front-end) check, just use ```i2b2.PM.model.isAdmin``` to verify if the user is admin or not.

**Comment by kvb2univpitt** [comment]
Done.
